config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  resources :events, :except => [:destroy] do
    resources :tickets, :except => [:destroy, :update]do
      collection do
        post 'buy', to: 'tickets#buy'
      end
    end
    collection do
      get 'my_events', to: 'events#my_events'
      post ':id', to: 'events#update'
      post ':id/publish', to: 'events#publish', as: :publish_event
    end
  end

  get '/login', to: 'users#show_login_form'
  post '/login', to: 'users#do_login'

  post '/logout', to: 'users#do_logout'

  get '/register', to: 'users#show_register_form'
  post '/register', to: 'users#do_create_user'

  get '/venues', to: 'venues#show_venues_list'
  get '/venues/new', to: 'venues#show_new_venue_form', as: :new_venue
  post '/venues/new', to: 'venues#create_new_venue'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :venue
  belongs_to :category
  belongs_to :creator, class_name: User

  has_many :ticket_types
  has_many :event_admins
  has_many :admins, class_name: User, through: :event_admins

  after_create :add_creator_as_admin

  validates_presence_of :extended_html_description, :venue, :category, :starts_at
  validates_uniqueness_of :name, uniqueness: {scope: [:venue, :starts_at]}

  def published?
    published
  end

  def outdated?
    starts_at < Date.today
  end

  def can_publish?
    !published? && ticket_types.count > 0
  end

  private
  def add_creator_as_admin
    EventAdmin.create({admin_id: creator_id, event_id: id})
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper

  before_action :require_login, only: [:new, :my_events, :edit, :update, :publish]
  before_action :load_data_for_event_form, only: [:new, :edit]
  before_action :find_event, only: [:show, :edit, :publish, :update]

  def index
    @events = Event.where('starts_at >= ? and published = true', Date.today).order(starts_at: 'desc')
    if params[:search]
      @events = @events.where('name like ?', "%#{params[:search]}%")
    end
  end

  def show
    @related_events = Event
                          .joins(:category)
                          .joins(:venue)
                          .joins('inner join regions on regions.id = venues.region_id')
                          .where('events.id <> ? and regions.id = ? and categories.id = ?', @event.id, @event.venue.region_id, @event.category.id)
  end

  def new
    @event = Event.new(hero_image_url: 'http://media.mangtinmoi.com/files/news/2015/09/thim-ha-la-ai-va-vi-sao-ca-sy-vu-ha-bi-goi-la-thim-ha-mot.jpeg')
  end

  def my_events
    @events = current_user.managing_events.order(starts_at: 'desc')
  end

  def create
    create_new_event
    redirect_to(my_events_events_path)
  end

  def edit
    redirect_to(my_events_events_path) unless can_edit?(@event)
  end

  def update
    if can_edit?(@event)
      update_event
      redirect_to event_path(params[:id])
    else
      flash[:error] = 'You do not have permission to update this event'
      redirect_to my_events_events_path
    end
  end

  def publish
    if can_edit?(@event)
      if params[:event][:publish] == 'true'
        if @event.can_publish?
          @event.published = true
          @event.save
          flash[:success] = 'Your event has been published'
        else
          flash[:error] = 'Your event needs at least 1 ticket type before it can be published'
        end
      elsif params[:event][:publish] == 'false'
        @event.published = false
        @event.save
        flash[:success] = 'Your event has been unpublished'
      end
      redirect_to(edit_event_path(@event))
    else
      flash[:error] = 'You do not have permission to edit this event'
      redirect_to(event_path(@event))
    end
  end

  private
  def find_event
    @event = Event.find(params[:id])
  end

  def event_params
    params
        .require(:event)
        .permit(:name, :category_id, :extended_html_description, :hero_image_url, :venue_id, :starts_at, :ends_at, :creator_id)
  end

  def create_new_event
    new_event = Event.create(event_params.merge(:creator_id => current_user.id))
    create_event_admins(new_event)
    new_event
  end

  def update_event
    @event.update(event_params)
    remove_event_admins(@event)
    create_event_admins(@event)
  end

  def create_event_admins(event)
    event_admins = []
    params[:event][:admins].try(:each) do |user_id|
      event_admins << {admin_id: user_id, event_id: event.id}
    end
    EventAdmin.create(event_admins)
  end

  def remove_event_admins(event)
    EventAdmin.where('event_id = ? and admin_id <> ?', event.id, event.creator_id).delete_all
  end

  def load_data_for_event_form
    @categories = Category.all
    @venues = Venue.all
    @admins = User.where('id <> ?', current_user.id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def header_background_image_url
   image_path('color-me-run.jpg')
  end

  def edit_button(event)
    if can_edit?(event)
      link_to('Edit', edit_event_path(event), class: 'btn btn-primary btn-lg btn-block')
    end
  end

  def can_edit?(event)
    authenticated? && event.admins.ids.include?(current_user.id)
  end
end

app/views/events/_card.html.erb
<div class="col-md-6">
  <%= link_to event_path(event) do %>
      <div class="card">
        <img class="card-img-top" src="<%= event.hero_image_url %>">
        <div class="card-block">
          <h4 class="card-title">
            <%= event.name %>
            <% if action_name == 'my_events' %>
                <% if event.starts_at < Date.today %>
                    <span class="label label-danger">Outdated</span>
                <% end %>
                <% if event.published? %>
                    <span class="label label-success">Published</span>
                <% else %>
                    <span class="label label-default">Draft</span>
                <% end %>
            <% end %>
          </h4>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
            content.
          </p>
        </div>
      </div>
  <% end %>
</div>  

app/views/events/_form.html.erb
<form method="<%= form_method %>" action="<%= form_action %>">
  <%= token_tag %>
  <div class="form-group">
    <label for="event[name]">Name</label>
    <input type="text" class="form-control" id="event[name]" name="event[name]" placeholder="Superbowl" value="<%= @event.name %>"/>
  </div>
  <div class="form-group">
    <label for="event[category_id]">Category</label>
    <select id="event[category_id]" name="event[category_id]" class="form-control">
      <% @categories.each do |cat| %>
          <option <%= cat.id == @event.category.try(:id) ? 'selected' : '' %> value="<%= cat.id %>"><%= cat.name %></option>
      <% end %>
    </select>
  </div>
  <div class="form-group">
    <label for="event[extended_html_description]">Description</label>
        <textarea id="event[extended_html_description]" name="event[extended_html_description]"
                  placeholder="Super awesome tournament" class="form-control"><%= @event.extended_html_description %></textarea>
  </div>
  <div class="form-group">
    <label for="event[hero_image_url]">Image</label>
    <input type="text" class="form-control" id="event[hero_image_url]" name="event[hero_image_url]"
           placeholder="www.google.com"
           value="<%= @event.hero_image_url %>"/>
  </div>
  <div class="form-group">
    <label for="event[venue_id]">Venue</label>
    <select id="event[venue_id]" name="event[venue_id]" class="form-control">
      <% @venues.each do |venue| %>
          <option <%= venue.id == @event.venue.try(:id) ? 'selected' : '' %> value="<%= venue.id %>"><%= venue.name %></option>
      <% end %>
    </select>
  </div>
  <div class="form-group">
    <label for="event[starts_at]">Start</label>
    <input type="date" class="form-control" id="event[starts_at]" name="event[starts_at]" value="<%= @event.starts_at.try(:strftime, '%Y-%m-%d') %>"/>
  </div>
  <div class="form-group">
    <label for="event[ends_at]">End</label>
    <input type="date" class="form-control" id="event[ends_at]" name="event[ends_at]" value="<%= @event.ends_at.try(:strftime, '%Y-%m-%d') %>"/>
  </div>
  <div class="form-group">
    <label for="event[admins]">Admins</label>
    <select id="event[admins]" name="event[admins][]" class="form-control" multiple>
      <% @admins.each do |admin| %>
          <option <%= @event.admins.ids.include?(admin.id) ? 'selected' : '' %> value="<%= admin.id %>"><%= admin.name %></option>
      <% end %>
    </select>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>

app/views/events/edit.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'></div>
<div class="container-fluid">
  <div class="col-md-8">
    <h2>Event information</h2>
    <%= flash_messages %>

    <%= render partial: 'form', locals: {form_method: 'post', form_action: event_path(@event.id)} %>

    <hr/>

    <h2>Ticket types</h2>
    <form method="post" action="<%= event_tickets_path(@event.id) %>" class="form-inline">
      <%= token_tag %>
      <table class="table table-striped table-hover center-block">
        <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>Max quantity</th>
          <th>Min quantity</th>
        </tr>
        </thead>
        <tbody>
        <% @event.ticket_types.each do |type| %>
            <tr>
              <td><%= type.name %></td>
              <td><%= type.price %></td>
              <td><%= type.max_quantity %></td>
              <td><%= type.min_quantity %></td>
            </tr>
        <% end %>
        <tr>
          <td><input class="form-control" type="text" id="ticket[name]" name="ticket[name]" placeholder="VIP"/></td>
          <td><input class="form-control" type="text" id="ticket[price]" name="ticket[price]" placeholder="10000"/></td>
          <td>
            <input class="form-control" type="text" id="ticket[max_quantity]" name="ticket[max_quantity]" placeholder="100"/>
          </td>
          <td>
            <input class="form-control" type="text" id="ticket[min_quantity]" name="ticket[min_quantity]" placeholder="1"/>
            <button class="btn btn-primary" type="submit">Add</button>
          </td>
        </tr>
        </tbody>
      </table>
    </form>
    <br/>
    <h2>Publish</h2>
    <% if @event.published? %>
        <form method="post" action="<%= publish_event_events_path(@event) %>">
          <%= token_tag %>
          <input type="hidden" id="event[publish]" name="event[publish]" value="false"/>
          <button class="btn btn-warning" type="submit">Unpublish</button>
        </form>
    <% elsif @event.can_publish? %>
        <form method="post" action="<%= publish_event_events_path(@event) %>">
          <%= token_tag %>
          <input type="hidden" id="event[publish]" name="event[publish]" value="true"/>
          <button class="btn btn-success" type="submit">Publish</button>
        </form>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'>
  <div class="container">
    <h2> Discover upcoming events </h2>
    <form>
      <input type="text" class="form-control" name="search" placeholder="Search for events, shows, courses...">
    </form>
  </div>
</div>
<div class="container-fluid events-list">
  <% @events.in_groups_of(2) do |g| %>
      <div class="row">
        <% g.compact.each do |e| %>
            <%= render partial: 'card', locals: {event: e} %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/events/my_events.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'></div>
<div class="container-fluid events-list">
  <h2>My managing events</h2>
  <% @events.in_groups_of(2) do |g| %>
      <div class="row">
        <% g.compact.each do |e| %>
            <%= render partial: 'card', locals: {event: e} %>
        <% end %>
      </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'></div>
<div class="container-fluid">
  <div class="col-md-8">
    <h2>Create a new event</h2>
    <%= render partial: 'form', locals: {form_method: 'post', form_action: events_path} %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container-fluid no-pad events-detail">
  <div class="row no-pad">
    <div class="col-md-3 sidebar">
      <p>
        <%= fa_icon 'ticket' %>
        Price
      </p>
      <h1> Hot Events </h1>
      <div class="ticket-list">
        <% @event.ticket_types.each do |ticket_type| %>
            <div class="row">
              <div class="col-md-6">
                <%= ticket_type.name %>
              </div>

              <div class="col-md-6 price text-right">
                <%= number_to_currency(ticket_type.price, unit: 'VND', precision: 0) %>
              </div>
            </div>
            <div class="clearfix"></div>
        <% end %>
        <% if @event.published? && !@event.outdated? %>
            <%= link_to new_event_ticket_path(@event) do %>
                <button class='btn btn-lg btn-block btn-danger'> BOOK NOW</button>
            <% end %>
        <% end %>
        <br/>
        <%= edit_button(@event) %>
      </div>
    </div>
    <div class="col-md-9 event-content">
      <div class="hero-img hidden-sm-down" style="background-image: url(<%= @event.hero_image_url %>); background-size: cover;"></div>
      <div class="container">
        <h3> <%= @event.name %> </h3>
        <div class="pull-left">
          <%= fa_icon 'clock-o' %>
        </div>
        <div class="time-details">
          <%= @event.starts_at.strftime('%A, %d %b %Y %l:%M %p') %>
        </div>


        <div class="pull-left">
          <%= fa_icon 'map-marker' %>
        </div>
        <div class="venue-details">
          <%= @event.venue.name %>
          <br/>
          <%= @event.venue.full_address %>
        </div>

        <div class="img-spacer">
          <%= image_tag 'shadow-top.png' %>
        </div>
        <div class="extended-description">
          <%= @event.extended_html_description.html_safe %>
        </div>

      </div>
    </div>
    <div class="col-md-9 event-content">
      <div class="container">
        <h3>Related Event</h3>
        <% @related_events.each do |e| %>
            <div><a href="<%= event_path(e) %>"><%= "#{e.name} at #{e.venue.name}" %></a></div>
        <% end %>
      </div>
    </div>
  </div>

</div>