config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  resources :events, :except => [:destroy] do
    resources :tickets, :except => [:destroy, :update]do
      collection do
        post 'buy', to: 'tickets#buy'
      end
    end
    collection do
      get 'my_events', to: 'events#my_events'
      post ':id', to: 'events#update'
      post ':id/publish', to: 'events#publish', as: :publish_event
    end
  end

  get '/login', to: 'users#show_login_form'
  post '/login', to: 'users#do_login'

  post '/logout', to: 'users#do_logout'

  get '/register', to: 'users#show_register_form'
  post '/register', to: 'users#do_create_user'

  get '/venues', to: 'venues#show_venues_list'
  get '/venues/new', to: 'venues#show_new_venue_form', as: :new_venue
  post '/venues/new', to: 'venues#create_new_venue'
end

app/models/ticket_type.rb
class TicketType < ActiveRecord::Base
  belongs_to :event

  def min_quantity_to_purchase
    if !!min_quantity && 0 < min_quantity && min_quantity <= 10
      min_quantity
    else
      1
    end
  end

  def max_quantity_to_purchase
    if !!max_quantity && max_quantity <= 10
      max_quantity
    else
      10
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_action :require_login, only: [:create]
  before_action :find_event, only: [:new, :buy]

  def new
    redirect_to root_path unless @event.published? && !@event.outdated?
  end

  def create
    ticket_type = TicketType.new(ticket_params)
    ticket_type.event = Event.find(params[:event_id])
    ticket_type.save

    redirect_to(edit_event_path(params[:event_id]))
  end

  def buy
    if @event.outdated?
      flash[:error] = 'This event has expired. You cannot buy its ticket'
      redirect_to(event_path(event))
    else
      prepare_order
      flash.now[:success] = 'You have purchased tickets successfully. Below is your order.'
      render('tickets/buy')
    end
  end

  private

  def find_event
    @event = Event.find(params[:event_id])
  end

  def ticket_params
    params
        .require(:ticket)
        .permit(:name, :price, :max_quantity, :min_quantity)
  end

  def prepare_order
    @orders = []
    ticket_types = TicketType.where(id: params[:tickets].keys)
    ticket_types.each do |type|
      @orders.push({ticket_type: type, quantity: params[:tickets][type.id.to_s].to_i})
    end
    @total = @orders.inject(0) do |total, order|
      total + order[:ticket_type].price * order[:quantity]
    end
  end
end

app/views/tickets/buy.html.erb
<div class='events-header' style='background-image: url(<%= header_background_image_url %>)'></div>
<div class="container-fluid">
  <div class="col-md-8">
    <br/>
    <%= flash_messages %>
    <h2>Order information</h2>
    <h4>Event</h4>
    <div class="form-group">
      <label class="control-label">Name</label>
      <p class="form-control-static"><%= @event.name %></p>
    </div>
    <div class="form-group">
      <label class="control-label">Venue</label>
      <p class="form-control-static"><%= @event.venue.name %></p>
    </div>
    <br/>
    <hr/>
    <h4>Tickets</h4>
    <table class="table table-hover table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
      </thead>
      <tbody>
      <% @orders.each do |order| %>
          <tr>
            <td><%= order[:ticket_type].name %></td>
            <td><%= order[:quantity] %></td>
            <td><%= order[:ticket_type].price %></td>
          </tr>
      <% end %>
      </tbody>
      <tfoot>
      <tr>
        <td colspan="2"><b>Total</b></td>
        <td><%= @total %></td>
      </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/tickets/new.html.erb
<div class="container-fluid tickets-buy">
  <div class="row tickets-header">
    <div class="col-xs-12 col-md-11 col-md-offset-1">
      <h3> <%= @event.name %> </h3>
      <div class="pull-left">
        <%= fa_icon 'map-marker' %>
      </div>
      <div class="venue-details">
        <%= @event.venue.name %>
        <br/>
        <%= @event.venue.full_address %>
      </div>

      <div class="pull-left">
        <%= fa_icon 'clock-o' %>
      </div>
      <div class="time-details">
        <%= @event.starts_at.strftime('%A, %d %b %Y %l:%M %p') %>
      </div>
    </div>
  </div>
  <form method="post" action="<%= buy_event_tickets_path(@event) %>">
    <%= token_tag %>
    <div class="row">
      <div class="col-md-11 col-md-offset-1">
        <table class="table table-hover table-striped">
          <thead>
          <tr>
            <th>Ticket Type</th>
            <th>Unit Price</th>
            <th>Quantity</th>
          </tr>
          </thead>
          <tbody>
          <% @event.ticket_types.each do |type| %>
              <tr>
                <td><%= type.name %></td>
                <td><%= number_to_currency(type.price, unit: 'VND ', precision: 0) %></td>
                <td>
                  <select name="<%= "tickets[#{type.id}]" %>" class="form-control">
                    <option value="0">0</option>
                    <%= options_for_select((type.min_quantity_to_purchase)..(type.max_quantity_to_purchase)) %>
                  </select>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <button class="btn btn-success btn-lg btn-block" type="submit">Buy</button>
      </div>
    </div>
  </form>
</div>