config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  resources :events, :except => [:destroy] do
    resources :tickets, :except => [:destroy, :update]do
      collection do
        post 'buy', to: 'tickets#buy'
      end
    end
    collection do
      get 'my_events', to: 'events#my_events'
      post ':id', to: 'events#update'
      post ':id/publish', to: 'events#publish', as: :publish_event
    end
  end

  get '/login', to: 'users#show_login_form'
  post '/login', to: 'users#do_login'

  post '/logout', to: 'users#do_logout'

  get '/register', to: 'users#show_register_form'
  post '/register', to: 'users#do_create_user'

  get '/venues', to: 'venues#show_venues_list'
  get '/venues/new', to: 'venues#show_new_venue_form', as: :new_venue
  post '/venues/new', to: 'venues#create_new_venue'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coderticket</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
  <a class="navbar-brand" href="<%= root_path %>">Coder Ticket</a>
  <% if !authenticated? %>
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="<%= login_path %>">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= register_path %>">Sign Up</a>
        </li>
      </ul>
  <% end %>
  <% if authenticated? %>
      <ul class="nav navbar-nav">
        <li class="nav-item dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Events
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="<%= my_events_events_path %>">My events</a></li>
            <li><a href="<%= new_event_path %>">Create new event</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Venues
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="<%= venues_path %>">List</a></li>
            <li><a href="<%= new_venue_path %>">Create new venue</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right" id="right-nav-bar">
        <li class="nav-item">
          <form action="<%= logout_path %>" method="post">
            <%= token_tag %>
            <button class="btn btn-link navbar-btn" type="submit">Logout</button>
          </form>
        </li>
      </ul>
  <% end %>
</nav>
<%= yield %>

</body>
</html>

app/views/layouts/no_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsTemplate</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>